  services:
    postgres:
      image: postgres:14.8-alpine3.18
      environment:
        POSTGRES_DB: "postgres1"
        POSTGRES_USER: "postgres1"
        POSTGRES_PASSWORD: "postgres1"
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres1 -d postgres1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

    app:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        postgres:
          condition: service_healthy

  volumes:
    postgres_data: